use color_names::ColorNames;
use color::{Color, color_from_hex};

pub struct NtcColors {
}

impl ColorNames for NtcColors {
    fn get_colors(&self) -> Vec<Color> {
        return vec![
            color_from_hex("Black", "000000"),
            color_from_hex("Navy Blue", "000080"),
            color_from_hex("Dark Blue", "0000C8"),
            color_from_hex("Blue", "0000FF"),
            color_from_hex("Stratos", "000741"),
            color_from_hex("Swamp", "001B1C"),
            color_from_hex("Resolution Blue", "002387"),
            color_from_hex("Deep Fir", "002900"),
            color_from_hex("Burnham", "002E20"),
            color_from_hex("International Klein Blue", "002FA7"),
            color_from_hex("Prussian Blue", "003153"),
            color_from_hex("Midnight Blue", "003366"),
            color_from_hex("Smalt", "003399"),
            color_from_hex("Deep Teal", "003532"),
            color_from_hex("Cyprus", "003E40"),
            color_from_hex("Kaitoke Green", "004620"),
            color_from_hex("Cobalt", "0047AB"),
            color_from_hex("Crusoe", "004816"),
            color_from_hex("Sherpa Blue", "004950"),
            color_from_hex("Endeavour", "0056A7"),
            color_from_hex("Camarone", "00581A"),
            color_from_hex("Science Blue", "0066CC"),
            color_from_hex("Blue Ribbon", "0066FF"),
            color_from_hex("Tropical Rain Forest", "00755E"),
            color_from_hex("Allports", "0076A3"),
            color_from_hex("Deep Cerulean", "007BA7"),
            color_from_hex("Lochmara", "007EC7"),
            color_from_hex("Azure Radiance", "007FFF"),
            color_from_hex("Teal", "008080"),
            color_from_hex("Bondi Blue", "0095B6"),
            color_from_hex("Pacific Blue", "009DC4"),
            color_from_hex("Persian Green", "00A693"),
            color_from_hex("Jade", "00A86B"),
            color_from_hex("Caribbean Green", "00CC99"),
            color_from_hex("Robin's Egg Blue", "00CCCC"),
            color_from_hex("Green", "00FF00"),
            color_from_hex("Spring Green", "00FF7F"),
            color_from_hex("Cyan / Aqua", "00FFFF"),
            color_from_hex("Blue Charcoal", "010D1A"),
            color_from_hex("Midnight", "011635"),
            color_from_hex("Holly", "011D13"),
            color_from_hex("Daintree", "012731"),
            color_from_hex("Cardin Green", "01361C"),
            color_from_hex("County Green", "01371A"),
            color_from_hex("Astronaut Blue", "013E62"),
            color_from_hex("Regal Blue", "013F6A"),
            color_from_hex("Aqua Deep", "014B43"),
            color_from_hex("Orient", "015E85"),
            color_from_hex("Blue Stone", "016162"),
            color_from_hex("Fun Green", "016D39"),
            color_from_hex("Pine Green", "01796F"),
            color_from_hex("Blue Lagoon", "017987"),
            color_from_hex("Deep Sea", "01826B"),
            color_from_hex("Green Haze", "01A368"),
            color_from_hex("English Holly", "022D15"),
            color_from_hex("Sherwood Green", "02402C"),
            color_from_hex("Congress Blue", "02478E"),
            color_from_hex("Evening Sea", "024E46"),
            color_from_hex("Bahama Blue", "026395"),
            color_from_hex("Observatory", "02866F"),
            color_from_hex("Cerulean", "02A4D3"),
            color_from_hex("Tangaroa", "03163C"),
            color_from_hex("Green Vogue", "032B52"),
            color_from_hex("Mosque", "036A6E"),
            color_from_hex("Midnight Moss", "041004"),
            color_from_hex("Black Pearl", "041322"),
            color_from_hex("Blue Whale", "042E4C"),
            color_from_hex("Zuccini", "044022"),
            color_from_hex("Teal Blue", "044259"),
            color_from_hex("Deep Cove", "051040"),
            color_from_hex("Gulf Blue", "051657"),
            color_from_hex("Venice Blue", "055989"),
            color_from_hex("Watercourse", "056F57"),
            color_from_hex("Catalina Blue", "062A78"),
            color_from_hex("Tiber", "063537"),
            color_from_hex("Gossamer", "069B81"),
            color_from_hex("Niagara", "06A189"),
            color_from_hex("Tarawera", "073A50"),
            color_from_hex("Jaguar", "080110"),
            color_from_hex("Black Bean", "081910"),
            color_from_hex("Deep Sapphire", "082567"),
            color_from_hex("Elf Green", "088370"),
            color_from_hex("Bright Turquoise", "08E8DE"),
            color_from_hex("Downriver", "092256"),
            color_from_hex("Palm Green", "09230F"),
            color_from_hex("Madison", "09255D"),
            color_from_hex("Bottle Green", "093624"),
            color_from_hex("Deep Sea Green", "095859"),
            color_from_hex("Salem", "097F4B"),
            color_from_hex("Black Russian", "0A001C"),
            color_from_hex("Dark Fern", "0A480D"),
            color_from_hex("Japanese Laurel", "0A6906"),
            color_from_hex("Atoll", "0A6F75"),
            color_from_hex("Cod Gray", "0B0B0B"),
            color_from_hex("Marshland", "0B0F08"),
            color_from_hex("Gordons Green", "0B1107"),
            color_from_hex("Black Forest", "0B1304"),
            color_from_hex("San Felix", "0B6207"),
            color_from_hex("Malachite", "0BDA51"),
            color_from_hex("Ebony", "0C0B1D"),
            color_from_hex("Woodsmoke", "0C0D0F"),
            color_from_hex("Racing Green", "0C1911"),
            color_from_hex("Surfie Green", "0C7A79"),
            color_from_hex("Blue Chill", "0C8990"),
            color_from_hex("Black Rock", "0D0332"),
            color_from_hex("Bunker", "0D1117"),
            color_from_hex("Aztec", "0D1C19"),
            color_from_hex("Bush", "0D2E1C"),
            color_from_hex("Cinder", "0E0E18"),
            color_from_hex("Firefly", "0E2A30"),
            color_from_hex("Torea Bay", "0F2D9E"),
            color_from_hex("Vulcan", "10121D"),
            color_from_hex("Green Waterloo", "101405"),
            color_from_hex("Eden", "105852"),
            color_from_hex("Arapawa", "110C6C"),
            color_from_hex("Ultramarine", "120A8F"),
            color_from_hex("Elephant", "123447"),
            color_from_hex("Jewel", "126B40"),
            color_from_hex("Diesel", "130000"),
            color_from_hex("Asphalt", "130A06"),
            color_from_hex("Blue Zodiac", "13264D"),
            color_from_hex("Parsley", "134F19"),
            color_from_hex("Nero", "140600"),
            color_from_hex("Tory Blue", "1450AA"),
            color_from_hex("Bunting", "151F4C"),
            color_from_hex("Denim", "1560BD"),
            color_from_hex("Genoa", "15736B"),
            color_from_hex("Mirage", "161928"),
            color_from_hex("Hunter Green", "161D10"),
            color_from_hex("Big Stone", "162A40"),
            color_from_hex("Celtic", "163222"),
            color_from_hex("Timber Green", "16322C"),
            color_from_hex("Gable Green", "163531"),
            color_from_hex("Pine Tree", "171F04"),
            color_from_hex("Chathams Blue", "175579"),
            color_from_hex("Deep Forest Green", "182D09"),
            color_from_hex("Blumine", "18587A"),
            color_from_hex("Palm Leaf", "19330E"),
            color_from_hex("Nile Blue", "193751"),
            color_from_hex("Fun Blue", "1959A8"),
            color_from_hex("Lucky Point", "1A1A68"),
            color_from_hex("Mountain Meadow", "1AB385"),
            color_from_hex("Tolopea", "1B0245"),
            color_from_hex("Haiti", "1B1035"),
            color_from_hex("Deep Koamaru", "1B127B"),
            color_from_hex("Acadia", "1B1404"),
            color_from_hex("Seaweed", "1B2F11"),
            color_from_hex("Biscay", "1B3162"),
            color_from_hex("Matisse", "1B659D"),
            color_from_hex("Crowshead", "1C1208"),
            color_from_hex("Rangoon Green", "1C1E13"),
            color_from_hex("Persian Blue", "1C39BB"),
            color_from_hex("Everglade", "1C402E"),
            color_from_hex("Elm", "1C7C7D"),
            color_from_hex("Green Pea", "1D6142"),
            color_from_hex("Creole", "1E0F04"),
            color_from_hex("Karaka", "1E1609"),
            color_from_hex("El Paso", "1E1708"),
            color_from_hex("Cello", "1E385B"),
            color_from_hex("Te Papa Green", "1E433C"),
            color_from_hex("Dodger Blue", "1E90FF"),
            color_from_hex("Eastern Blue", "1E9AB0"),
            color_from_hex("Night Rider", "1F120F"),
            color_from_hex("Java", "1FC2C2"),
            color_from_hex("Jacksons Purple", "20208D"),
            color_from_hex("Cloud Burst", "202E54"),
            color_from_hex("Blue Dianne", "204852"),
            color_from_hex("Eternity", "211A0E"),
            color_from_hex("Deep Blue", "220878"),
            color_from_hex("Forest Green", "228B22"),
            color_from_hex("Mallard", "233418"),
            color_from_hex("Violet", "240A40"),
            color_from_hex("Kilamanjaro", "240C02"),
            color_from_hex("Log Cabin", "242A1D"),
            color_from_hex("Black Olive", "242E16"),
            color_from_hex("Green House", "24500F"),
            color_from_hex("Graphite", "251607"),
            color_from_hex("Cannon Black", "251706"),
            color_from_hex("Port Gore", "251F4F"),
            color_from_hex("Shark", "25272C"),
            color_from_hex("Green Kelp", "25311C"),
            color_from_hex("Curious Blue", "2596D1"),
            color_from_hex("Paua", "260368"),
            color_from_hex("Paris M", "26056A"),
            color_from_hex("Wood Bark", "261105"),
            color_from_hex("Gondola", "261414"),
            color_from_hex("Steel Gray", "262335"),
            color_from_hex("Ebony Clay", "26283B"),
            color_from_hex("Bay of Many", "273A81"),
            color_from_hex("Plantation", "27504B"),
            color_from_hex("Eucalyptus", "278A5B"),
            color_from_hex("Oil", "281E15"),
            color_from_hex("Astronaut", "283A77"),
            color_from_hex("Mariner", "286ACD"),
            color_from_hex("Violent Violet", "290C5E"),
            color_from_hex("Bastille", "292130"),
            color_from_hex("Zeus", "292319"),
            color_from_hex("Charade", "292937"),
            color_from_hex("Jelly Bean", "297B9A"),
            color_from_hex("Jungle Green", "29AB87"),
            color_from_hex("Cherry Pie", "2A0359"),
            color_from_hex("Coffee Bean", "2A140E"),
            color_from_hex("Baltic Sea", "2A2630"),
            color_from_hex("Turtle Green", "2A380B"),
            color_from_hex("Cerulean Blue", "2A52BE"),
            color_from_hex("Sepia Black", "2B0202"),
            color_from_hex("Valhalla", "2B194F"),
            color_from_hex("Heavy Metal", "2B3228"),
            color_from_hex("Blue Gem", "2C0E8C"),
            color_from_hex("Revolver", "2C1632"),
            color_from_hex("Bleached Cedar", "2C2133"),
            color_from_hex("Lochinvar", "2C8C84"),
            color_from_hex("Mikado", "2D2510"),
            color_from_hex("Outer Space", "2D383A"),
            color_from_hex("St Tropaz", "2D569B"),
            color_from_hex("Jacaranda", "2E0329"),
            color_from_hex("Jacko Bean", "2E1905"),
            color_from_hex("Rangitoto", "2E3222"),
            color_from_hex("Rhino", "2E3F62"),
            color_from_hex("Sea Green", "2E8B57"),
            color_from_hex("Scooter", "2EBFD4"),
            color_from_hex("Onion", "2F270E"),
            color_from_hex("Governor Bay", "2F3CB3"),
            color_from_hex("Sapphire", "2F519E"),
            color_from_hex("Spectra", "2F5A57"),
            color_from_hex("Casal", "2F6168"),
            color_from_hex("Melanzane", "300529"),
            color_from_hex("Cocoa Brown", "301F1E"),
            color_from_hex("Woodrush", "302A0F"),
            color_from_hex("San Juan", "304B6A"),
            color_from_hex("Turquoise", "30D5C8"),
            color_from_hex("Eclipse", "311C17"),
            color_from_hex("Pickled Bluewood", "314459"),
            color_from_hex("Azure", "315BA1"),
            color_from_hex("Calypso", "31728D"),
            color_from_hex("Paradiso", "317D82"),
            color_from_hex("Persian Indigo", "32127A"),
            color_from_hex("Blackcurrant", "32293A"),
            color_from_hex("Mine Shaft", "323232"),
            color_from_hex("Stromboli", "325D52"),
            color_from_hex("Bilbao", "327C14"),
            color_from_hex("Astral", "327DA0"),
            color_from_hex("Christalle", "33036B"),
            color_from_hex("Thunder", "33292F"),
            color_from_hex("Shamrock", "33CC99"),
            color_from_hex("Tamarind", "341515"),
            color_from_hex("Mardi Gras", "350036"),
            color_from_hex("Valentino", "350E42"),
            color_from_hex("Jagger", "350E57"),
            color_from_hex("Tuna", "353542"),
            color_from_hex("Chambray", "354E8C"),
            color_from_hex("Martinique", "363050"),
            color_from_hex("Tuatara", "363534"),
            color_from_hex("Waiouru", "363C0D"),
            color_from_hex("Ming", "36747D"),
            color_from_hex("La Palma", "368716"),
            color_from_hex("Chocolate", "370202"),
            color_from_hex("Clinker", "371D09"),
            color_from_hex("Brown Tumbleweed", "37290E"),
            color_from_hex("Birch", "373021"),
            color_from_hex("Oracle", "377475"),
            color_from_hex("Blue Diamond", "380474"),
            color_from_hex("Grape", "381A51"),
            color_from_hex("Dune", "383533"),
            color_from_hex("Oxford Blue", "384555"),
            color_from_hex("Clover", "384910"),
            color_from_hex("Limed Spruce", "394851"),
            color_from_hex("Dell", "396413"),
            color_from_hex("Toledo", "3A0020"),
            color_from_hex("Sambuca", "3A2010"),
            color_from_hex("Jacarta", "3A2A6A"),
            color_from_hex("William", "3A686C"),
            color_from_hex("Killarney", "3A6A47"),
            color_from_hex("Keppel", "3AB09E"),
            color_from_hex("Temptress", "3B000B"),
            color_from_hex("Aubergine", "3B0910"),
            color_from_hex("Jon", "3B1F1F"),
            color_from_hex("Treehouse", "3B2820"),
            color_from_hex("Amazon", "3B7A57"),
            color_from_hex("Boston Blue", "3B91B4"),
            color_from_hex("Windsor", "3C0878"),
            color_from_hex("Rebel", "3C1206"),
            color_from_hex("Meteorite", "3C1F76"),
            color_from_hex("Dark Ebony", "3C2005"),
            color_from_hex("Camouflage", "3C3910"),
            color_from_hex("Bright Gray", "3C4151"),
            color_from_hex("Cape Cod", "3C4443"),
            color_from_hex("Lunar Green", "3C493A"),
            color_from_hex("Bean  ", "3D0C02"),
            color_from_hex("Bistre", "3D2B1F"),
            color_from_hex("Goblin", "3D7D52"),
            color_from_hex("Kingfisher Daisy", "3E0480"),
            color_from_hex("Cedar", "3E1C14"),
            color_from_hex("English Walnut", "3E2B23"),
            color_from_hex("Black Marlin", "3E2C1C"),
            color_from_hex("Ship Gray", "3E3A44"),
            color_from_hex("Pelorous", "3EABBF"),
            color_from_hex("Bronze", "3F2109"),
            color_from_hex("Cola", "3F2500"),
            color_from_hex("Madras", "3F3002"),
            color_from_hex("Minsk", "3F307F"),
            color_from_hex("Cabbage Pont", "3F4C3A"),
            color_from_hex("Tom Thumb", "3F583B"),
            color_from_hex("Mineral Green", "3F5D53"),
            color_from_hex("Puerto Rico", "3FC1AA"),
            color_from_hex("Harlequin", "3FFF00"),
            color_from_hex("Brown Pod", "401801"),
            color_from_hex("Cork", "40291D"),
            color_from_hex("Masala", "403B38"),
            color_from_hex("Thatch Green", "403D19"),
            color_from_hex("Fiord", "405169"),
            color_from_hex("Viridian", "40826D"),
            color_from_hex("Chateau Green", "40A860"),
            color_from_hex("Ripe Plum", "410056"),
            color_from_hex("Paco", "411F10"),
            color_from_hex("Deep Oak", "412010"),
            color_from_hex("Merlin", "413C37"),
            color_from_hex("Gun Powder", "414257"),
            color_from_hex("East Bay", "414C7D"),
            color_from_hex("Royal Blue", "4169E1"),
            color_from_hex("Ocean Green", "41AA78"),
            color_from_hex("Burnt Maroon", "420303"),
            color_from_hex("Lisbon Brown", "423921"),
            color_from_hex("Faded Jade", "427977"),
            color_from_hex("Scarlet Gum", "431560"),
            color_from_hex("Iroko", "433120"),
            color_from_hex("Armadillo", "433E37"),
            color_from_hex("River Bed", "434C59"),
            color_from_hex("Green Leaf", "436A0D"),
            color_from_hex("Barossa", "44012D"),
            color_from_hex("Morocco Brown", "441D00"),
            color_from_hex("Mako", "444954"),
            color_from_hex("Kelp", "454936"),
            color_from_hex("San Marino", "456CAC"),
            color_from_hex("Picton Blue", "45B1E8"),
            color_from_hex("Loulou", "460B41"),
            color_from_hex("Crater Brown", "462425"),
            color_from_hex("Gray Asparagus", "465945"),
            color_from_hex("Steel Blue", "4682B4"),
            color_from_hex("Rustic Red", "480404"),
            color_from_hex("Bulgarian Rose", "480607"),
            color_from_hex("Clairvoyant", "480656"),
            color_from_hex("Cocoa Bean", "481C1C"),
            color_from_hex("Woody Brown", "483131"),
            color_from_hex("Taupe", "483C32"),
            color_from_hex("Van Cleef", "49170C"),
            color_from_hex("Brown Derby", "492615"),
            color_from_hex("Metallic Bronze", "49371B"),
            color_from_hex("Verdun Green", "495400"),
            color_from_hex("Blue Bayoux", "496679"),
            color_from_hex("Bismark", "497183"),
            color_from_hex("Bracken", "4A2A04"),
            color_from_hex("Deep Bronze", "4A3004"),
            color_from_hex("Mondo", "4A3C30"),
            color_from_hex("Tundora", "4A4244"),
            color_from_hex("Gravel", "4A444B"),
            color_from_hex("Trout", "4A4E5A"),
            color_from_hex("Pigment Indigo", "4B0082"),
            color_from_hex("Nandor", "4B5D52"),
            color_from_hex("Saddle", "4C3024"),
            color_from_hex("Abbey", "4C4F56"),
            color_from_hex("Blackberry", "4D0135"),
            color_from_hex("Cab Sav", "4D0A18"),
            color_from_hex("Indian Tan", "4D1E01"),
            color_from_hex("Cowboy", "4D282D"),
            color_from_hex("Livid Brown", "4D282E"),
            color_from_hex("Rock", "4D3833"),
            color_from_hex("Punga", "4D3D14"),
            color_from_hex("Bronzetone", "4D400F"),
            color_from_hex("Woodland", "4D5328"),
            color_from_hex("Mahogany", "4E0606"),
            color_from_hex("Bossanova", "4E2A5A"),
            color_from_hex("Matterhorn", "4E3B41"),
            color_from_hex("Bronze Olive", "4E420C"),
            color_from_hex("Mulled Wine", "4E4562"),
            color_from_hex("Axolotl", "4E6649"),
            color_from_hex("Wedgewood", "4E7F9E"),
            color_from_hex("Shakespeare", "4EABD1"),
            color_from_hex("Honey Flower", "4F1C70"),
            color_from_hex("Daisy Bush", "4F2398"),
            color_from_hex("Indigo", "4F69C6"),
            color_from_hex("Fern Green", "4F7942"),
            color_from_hex("Fruit Salad", "4F9D5D"),
            color_from_hex("Apple", "4FA83D"),
            color_from_hex("Mortar", "504351"),
            color_from_hex("Kashmir Blue", "507096"),
            color_from_hex("Cutty Sark", "507672"),
            color_from_hex("Emerald", "50C878"),
            color_from_hex("Emperor", "514649"),
            color_from_hex("Chalet Green", "516E3D"),
            color_from_hex("Como", "517C66"),
            color_from_hex("Smalt Blue", "51808F"),
            color_from_hex("Castro", "52001F"),
            color_from_hex("Maroon Oak", "520C17"),
            color_from_hex("Gigas", "523C94"),
            color_from_hex("Voodoo", "533455"),
            color_from_hex("Victoria", "534491"),
            color_from_hex("Hippie Green", "53824B"),
            color_from_hex("Heath", "541012"),
            color_from_hex("Judge Gray", "544333"),
            color_from_hex("Fuscous Gray", "54534D"),
            color_from_hex("Vida Loca", "549019"),
            color_from_hex("Cioccolato", "55280C"),
            color_from_hex("Saratoga", "555B10"),
            color_from_hex("Finlandia", "556D56"),
            color_from_hex("Havelock Blue", "5590D9"),
            color_from_hex("Fountain Blue", "56B4BE"),
            color_from_hex("Spring Leaves", "578363"),
            color_from_hex("Saddle Brown", "583401"),
            color_from_hex("Scarpa Flow", "585562"),
            color_from_hex("Cactus", "587156"),
            color_from_hex("Hippie Blue", "589AAF"),
            color_from_hex("Wine Berry", "591D35"),
            color_from_hex("Brown Bramble", "592804"),
            color_from_hex("Congo Brown", "593737"),
            color_from_hex("Millbrook", "594433"),
            color_from_hex("Waikawa Gray", "5A6E9C"),
            color_from_hex("Horizon", "5A87A0"),
            color_from_hex("Jambalaya", "5B3013"),
            color_from_hex("Bordeaux", "5C0120"),
            color_from_hex("Mulberry Wood", "5C0536"),
            color_from_hex("Carnaby Tan", "5C2E01"),
            color_from_hex("Comet", "5C5D75"),
            color_from_hex("Redwood", "5D1E0F"),
            color_from_hex("Don Juan", "5D4C51"),
            color_from_hex("Chicago", "5D5C58"),
            color_from_hex("Verdigris", "5D5E37"),
            color_from_hex("Dingley", "5D7747"),
            color_from_hex("Breaker Bay", "5DA19F"),
            color_from_hex("Kabul", "5E483E"),
            color_from_hex("Hemlock", "5E5D3B"),
            color_from_hex("Irish Coffee", "5F3D26"),
            color_from_hex("Mid Gray", "5F5F6E"),
            color_from_hex("Shuttle Gray", "5F6672"),
            color_from_hex("Aqua Forest", "5FA777"),
            color_from_hex("Tradewind", "5FB3AC"),
            color_from_hex("Horses Neck", "604913"),
            color_from_hex("Smoky", "605B73"),
            color_from_hex("Corduroy", "606E68"),
            color_from_hex("Danube", "6093D1"),
            color_from_hex("Espresso", "612718"),
            color_from_hex("Eggplant", "614051"),
            color_from_hex("Costa Del Sol", "615D30"),
            color_from_hex("Glade Green", "61845F"),
            color_from_hex("Buccaneer", "622F30"),
            color_from_hex("Quincy", "623F2D"),
            color_from_hex("Butterfly Bush", "624E9A"),
            color_from_hex("West Coast", "625119"),
            color_from_hex("Finch", "626649"),
            color_from_hex("Patina", "639A8F"),
            color_from_hex("Fern", "63B76C"),
            color_from_hex("Blue Violet", "6456B7"),
            color_from_hex("Dolphin", "646077"),
            color_from_hex("Storm Dust", "646463"),
            color_from_hex("Siam", "646A54"),
            color_from_hex("Nevada", "646E75"),
            color_from_hex("Cornflower Blue", "6495ED"),
            color_from_hex("Viking", "64CCDB"),
            color_from_hex("Rosewood", "65000B"),
            color_from_hex("Cherrywood", "651A14"),
            color_from_hex("Purple Heart", "652DC1"),
            color_from_hex("Fern Frond", "657220"),
            color_from_hex("Willow Grove", "65745D"),
            color_from_hex("Hoki", "65869F"),
            color_from_hex("Pompadour", "660045"),
            color_from_hex("Purple", "660099"),
            color_from_hex("Tyrian Purple", "66023C"),
            color_from_hex("Dark Tan", "661010"),
            color_from_hex("Silver Tree", "66B58F"),
            color_from_hex("Bright Green", "66FF00"),
            color_from_hex("Screamin' Green", "66FF66"),
            color_from_hex("Black Rose", "67032D"),
            color_from_hex("Scampi", "675FA6"),
            color_from_hex("Ironside Gray", "676662"),
            color_from_hex("Viridian Green", "678975"),
            color_from_hex("Christi", "67A712"),
            color_from_hex("Nutmeg Wood Finish", "683600"),
            color_from_hex("Zambezi", "685558"),
            color_from_hex("Salt Box", "685E6E"),
            color_from_hex("Tawny Port", "692545"),
            color_from_hex("Finn", "692D54"),
            color_from_hex("Scorpion", "695F62"),
            color_from_hex("Lynch", "697E9A"),
            color_from_hex("Spice", "6A442E"),
            color_from_hex("Himalaya", "6A5D1B"),
            color_from_hex("Soya Bean", "6A6051"),
            color_from_hex("Hairy Heath", "6B2A14"),
            color_from_hex("Royal Purple", "6B3FA0"),
            color_from_hex("Shingle Fawn", "6B4E31"),
            color_from_hex("Dorado", "6B5755"),
            color_from_hex("Bermuda Gray", "6B8BA2"),
            color_from_hex("Olive Drab", "6B8E23"),
            color_from_hex("Eminence", "6C3082"),
            color_from_hex("Turquoise Blue", "6CDAE7"),
            color_from_hex("Lonestar", "6D0101"),
            color_from_hex("Pine Cone", "6D5E54"),
            color_from_hex("Dove Gray", "6D6C6C"),
            color_from_hex("Juniper", "6D9292"),
            color_from_hex("Gothic", "6D92A1"),
            color_from_hex("Red Oxide", "6E0902"),
            color_from_hex("Moccaccino", "6E1D14"),
            color_from_hex("Pickled Bean", "6E4826"),
            color_from_hex("Dallas", "6E4B26"),
            color_from_hex("Kokoda", "6E6D57"),
            color_from_hex("Pale Sky", "6E7783"),
            color_from_hex("Cafe Royale", "6F440C"),
            color_from_hex("Flint", "6F6A61"),
            color_from_hex("Highland", "6F8E63"),
            color_from_hex("Limeade", "6F9D02"),
            color_from_hex("Downy", "6FD0C5"),
            color_from_hex("Persian Plum", "701C1C"),
            color_from_hex("Sepia", "704214"),
            color_from_hex("Antique Bronze", "704A07"),
            color_from_hex("Ferra", "704F50"),
            color_from_hex("Coffee", "706555"),
            color_from_hex("Slate Gray", "708090"),
            color_from_hex("Cedar Wood Finish", "711A00"),
            color_from_hex("Metallic Copper", "71291D"),
            color_from_hex("Affair", "714693"),
            color_from_hex("Studio", "714AB2"),
            color_from_hex("Tobacco Brown", "715D47"),
            color_from_hex("Yellow Metal", "716338"),
            color_from_hex("Peat", "716B56"),
            color_from_hex("Olivetone", "716E10"),
            color_from_hex("Storm Gray", "717486"),
            color_from_hex("Sirocco", "718080"),
            color_from_hex("Aquamarine Blue", "71D9E2"),
            color_from_hex("Venetian Red", "72010F"),
            color_from_hex("Old Copper", "724A2F"),
            color_from_hex("Go Ben", "726D4E"),
            color_from_hex("Raven", "727B89"),
            color_from_hex("Seance", "731E8F"),
            color_from_hex("Raw Umber", "734A12"),
            color_from_hex("Kimberly", "736C9F"),
            color_from_hex("Crocodile", "736D58"),
            color_from_hex("Crete", "737829"),
            color_from_hex("Xanadu", "738678"),
            color_from_hex("Spicy Mustard", "74640D"),
            color_from_hex("Limed Ash", "747D63"),
            color_from_hex("Rolling Stone", "747D83"),
            color_from_hex("Blue Smoke", "748881"),
            color_from_hex("Laurel", "749378"),
            color_from_hex("Mantis", "74C365"),
            color_from_hex("Russett", "755A57"),
            color_from_hex("Deluge", "7563A8"),
            color_from_hex("Cosmic", "76395D"),
            color_from_hex("Blue Marguerite", "7666C6"),
            color_from_hex("Lima", "76BD17"),
            color_from_hex("Sky Blue", "76D7EA"),
            color_from_hex("Dark Burgundy", "770F05"),
            color_from_hex("Crown of Thorns", "771F1F"),
            color_from_hex("Walnut", "773F1A"),
            color_from_hex("Pablo", "776F61"),
            color_from_hex("Pacifika", "778120"),
            color_from_hex("Oxley", "779E86"),
            color_from_hex("Pastel Green", "77DD77"),
            color_from_hex("Japanese Maple", "780109"),
            color_from_hex("Mocha", "782D19"),
            color_from_hex("Peanut", "782F16"),
            color_from_hex("Camouflage Green", "78866B"),
            color_from_hex("Wasabi", "788A25"),
            color_from_hex("Ship Cove", "788BBA"),
            color_from_hex("Sea Nymph", "78A39C"),
            color_from_hex("Roman Coffee", "795D4C"),
            color_from_hex("Old Lavender", "796878"),
            color_from_hex("Rum", "796989"),
            color_from_hex("Fedora", "796A78"),
            color_from_hex("Sandstone", "796D62"),
            color_from_hex("Spray", "79DEEC"),
            color_from_hex("Siren", "7A013A"),
            color_from_hex("Fuchsia Blue", "7A58C1"),
            color_from_hex("Boulder", "7A7A7A"),
            color_from_hex("Wild Blue Yonder", "7A89B8"),
            color_from_hex("De York", "7AC488"),
            color_from_hex("Red Beech", "7B3801"),
            color_from_hex("Cinnamon", "7B3F00"),
            color_from_hex("Yukon Gold", "7B6608"),
            color_from_hex("Tapa", "7B7874"),
            color_from_hex("Waterloo ", "7B7C94"),
            color_from_hex("Flax Smoke", "7B8265"),
            color_from_hex("Amulet", "7B9F80"),
            color_from_hex("Asparagus", "7BA05B"),
            color_from_hex("Kenyan Copper", "7C1C05"),
            color_from_hex("Pesto", "7C7631"),
            color_from_hex("Topaz", "7C778A"),
            color_from_hex("Concord", "7C7B7A"),
            color_from_hex("Jumbo", "7C7B82"),
            color_from_hex("Trendy Green", "7C881A"),
            color_from_hex("Gumbo", "7CA1A6"),
            color_from_hex("Acapulco", "7CB0A1"),
            color_from_hex("Neptune", "7CB7BB"),
            color_from_hex("Pueblo", "7D2C14"),
            color_from_hex("Bay Leaf", "7DA98D"),
            color_from_hex("Malibu", "7DC8F7"),
            color_from_hex("Bermuda", "7DD8C6"),
            color_from_hex("Copper Canyon", "7E3A15"),
            color_from_hex("Claret", "7F1734"),
            color_from_hex("Peru Tan", "7F3A02"),
            color_from_hex("Falcon", "7F626D"),
            color_from_hex("Mobster", "7F7589"),
            color_from_hex("Moody Blue", "7F76D3"),
            color_from_hex("Chartreuse", "7FFF00"),
            color_from_hex("Aquamarine", "7FFFD4"),
            color_from_hex("Maroon", "800000"),
            color_from_hex("Rose Bud Cherry", "800B47"),
            color_from_hex("Falu Red", "801818"),
            color_from_hex("Red Robin", "80341F"),
            color_from_hex("Vivid Violet", "803790"),
            color_from_hex("Russet", "80461B"),
            color_from_hex("Friar Gray", "807E79"),
            color_from_hex("Olive", "808000"),
            color_from_hex("Gray", "808080"),
            color_from_hex("Gulf Stream", "80B3AE"),
            color_from_hex("Glacier", "80B3C4"),
            color_from_hex("Seagull", "80CCEA"),
            color_from_hex("Nutmeg", "81422C"),
            color_from_hex("Spicy Pink", "816E71"),
            color_from_hex("Empress", "817377"),
            color_from_hex("Spanish Green", "819885"),
            color_from_hex("Sand Dune", "826F65"),
            color_from_hex("Gunsmoke", "828685"),
            color_from_hex("Battleship Gray", "828F72"),
            color_from_hex("Merlot", "831923"),
            color_from_hex("Shadow", "837050"),
            color_from_hex("Chelsea Cucumber", "83AA5D"),
            color_from_hex("Monte Carlo", "83D0C6"),
            color_from_hex("Plum", "843179"),
            color_from_hex("Granny Smith", "84A0A0"),
            color_from_hex("Chetwode Blue", "8581D9"),
            color_from_hex("Bandicoot", "858470"),
            color_from_hex("Bali Hai", "859FAF"),
            color_from_hex("Half Baked", "85C4CC"),
            color_from_hex("Red Devil", "860111"),
            color_from_hex("Lotus", "863C3C"),
            color_from_hex("Ironstone", "86483C"),
            color_from_hex("Bull Shot", "864D1E"),
            color_from_hex("Rusty Nail", "86560A"),
            color_from_hex("Bitter", "868974"),
            color_from_hex("Regent Gray", "86949F"),
            color_from_hex("Disco", "871550"),
            color_from_hex("Americano", "87756E"),
            color_from_hex("Hurricane", "877C7B"),
            color_from_hex("Oslo Gray", "878D91"),
            color_from_hex("Sushi", "87AB39"),
            color_from_hex("Spicy Mix", "885342"),
            color_from_hex("Kumera", "886221"),
            color_from_hex("Suva Gray", "888387"),
            color_from_hex("Avocado", "888D65"),
            color_from_hex("Camelot", "893456"),
            color_from_hex("Solid Pink", "893843"),
            color_from_hex("Cannon Pink", "894367"),
            color_from_hex("Makara", "897D6D"),
            color_from_hex("Burnt Umber", "8A3324"),
            color_from_hex("True V", "8A73D6"),
            color_from_hex("Clay Creek", "8A8360"),
            color_from_hex("Monsoon", "8A8389"),
            color_from_hex("Stack", "8A8F8A"),
            color_from_hex("Jordy Blue", "8AB9F1"),
            color_from_hex("Electric Violet", "8B00FF"),
            color_from_hex("Monarch", "8B0723"),
            color_from_hex("Corn Harvest", "8B6B0B"),
            color_from_hex("Olive Haze", "8B8470"),
            color_from_hex("Schooner", "8B847E"),
            color_from_hex("Natural Gray", "8B8680"),
            color_from_hex("Mantle", "8B9C90"),
            color_from_hex("Portage", "8B9FEE"),
            color_from_hex("Envy", "8BA690"),
            color_from_hex("Cascade", "8BA9A5"),
            color_from_hex("Riptide", "8BE6D8"),
            color_from_hex("Cardinal Pink", "8C055E"),
            color_from_hex("Mule Fawn", "8C472F"),
            color_from_hex("Potters Clay", "8C5738"),
            color_from_hex("Trendy Pink", "8C6495"),
            color_from_hex("Paprika", "8D0226"),
            color_from_hex("Sanguine Brown", "8D3D38"),
            color_from_hex("Tosca", "8D3F3F"),
            color_from_hex("Cement", "8D7662"),
            color_from_hex("Granite Green", "8D8974"),
            color_from_hex("Manatee", "8D90A1"),
            color_from_hex("Polo Blue", "8DA8CC"),
            color_from_hex("Red Berry", "8E0000"),
            color_from_hex("Rope", "8E4D1E"),
            color_from_hex("Opium", "8E6F70"),
            color_from_hex("Domino", "8E775E"),
            color_from_hex("Mamba", "8E8190"),
            color_from_hex("Nepal", "8EABC1"),
            color_from_hex("Pohutukawa", "8F021C"),
            color_from_hex("El Salva", "8F3E33"),
            color_from_hex("Korma", "8F4B0E"),
            color_from_hex("Squirrel", "8F8176"),
            color_from_hex("Vista Blue", "8FD6B4"),
            color_from_hex("Burgundy", "900020"),
            color_from_hex("Old Brick", "901E1E"),
            color_from_hex("Hemp", "907874"),
            color_from_hex("Almond Frost", "907B71"),
            color_from_hex("Sycamore", "908D39"),
            color_from_hex("Sangria", "92000A"),
            color_from_hex("Cumin", "924321"),
            color_from_hex("Beaver", "926F5B"),
            color_from_hex("Stonewall", "928573"),
            color_from_hex("Venus", "928590"),
            color_from_hex("Medium Purple", "9370DB"),
            color_from_hex("Cornflower", "93CCEA"),
            color_from_hex("Algae Green", "93DFB8"),
            color_from_hex("Copper Rust", "944747"),
            color_from_hex("Arrowtown", "948771"),
            color_from_hex("Scarlett", "950015"),
            color_from_hex("Strikemaster", "956387"),
            color_from_hex("Mountain Mist", "959396"),
            color_from_hex("Carmine", "960018"),
            color_from_hex("Brown", "964B00"),
            color_from_hex("Leather", "967059"),
            color_from_hex("Purple Mountain's Majesty", "9678B6"),
            color_from_hex("Lavender Purple", "967BB6"),
            color_from_hex("Pewter", "96A8A1"),
            color_from_hex("Summer Green", "96BBAB"),
            color_from_hex("Au Chico", "97605D"),
            color_from_hex("Wisteria", "9771B5"),
            color_from_hex("Atlantis", "97CD2D"),
            color_from_hex("Vin Rouge", "983D61"),
            color_from_hex("Lilac Bush", "9874D3"),
            color_from_hex("Bazaar", "98777B"),
            color_from_hex("Hacienda", "98811B"),
            color_from_hex("Pale Oyster", "988D77"),
            color_from_hex("Mint Green", "98FF98"),
            color_from_hex("Fresh Eggplant", "990066"),
            color_from_hex("Violet Eggplant", "991199"),
            color_from_hex("Tamarillo", "991613"),
            color_from_hex("Totem Pole", "991B07"),
            color_from_hex("Copper Rose", "996666"),
            color_from_hex("Amethyst", "9966CC"),
            color_from_hex("Mountbatten Pink", "997A8D"),
            color_from_hex("Blue Bell", "9999CC"),
            color_from_hex("Prairie Sand", "9A3820"),
            color_from_hex("Toast", "9A6E61"),
            color_from_hex("Gurkha", "9A9577"),
            color_from_hex("Olivine", "9AB973"),
            color_from_hex("Shadow Green", "9AC2B8"),
            color_from_hex("Oregon", "9B4703"),
            color_from_hex("Lemon Grass", "9B9E8F"),
            color_from_hex("Stiletto", "9C3336"),
            color_from_hex("Hawaiian Tan", "9D5616"),
            color_from_hex("Gull Gray", "9DACB7"),
            color_from_hex("Pistachio", "9DC209"),
            color_from_hex("Granny Smith Apple", "9DE093"),
            color_from_hex("Anakiwa", "9DE5FF"),
            color_from_hex("Chelsea Gem", "9E5302"),
            color_from_hex("Sepia Skin", "9E5B40"),
            color_from_hex("Sage", "9EA587"),
            color_from_hex("Citron", "9EA91F"),
            color_from_hex("Rock Blue", "9EB1CD"),
            color_from_hex("Morning Glory", "9EDEE0"),
            color_from_hex("Cognac", "9F381D"),
            color_from_hex("Reef Gold", "9F821C"),
            color_from_hex("Star Dust", "9F9F9C"),
            color_from_hex("Santas Gray", "9FA0B1"),
            color_from_hex("Sinbad", "9FD7D3"),
            color_from_hex("Feijoa", "9FDD8C"),
            color_from_hex("Tabasco", "A02712"),
            color_from_hex("Buttered Rum", "A1750D"),
            color_from_hex("Hit Gray", "A1ADB5"),
            color_from_hex("Citrus", "A1C50A"),
            color_from_hex("Aqua Island", "A1DAD7"),
            color_from_hex("Water Leaf", "A1E9DE"),
            color_from_hex("Flirt", "A2006D"),
            color_from_hex("Rouge", "A23B6C"),
            color_from_hex("Cape Palliser", "A26645"),
            color_from_hex("Gray Chateau", "A2AAB3"),
            color_from_hex("Edward", "A2AEAB"),
            color_from_hex("Pharlap", "A3807B"),
            color_from_hex("Amethyst Smoke", "A397B4"),
            color_from_hex("Blizzard Blue", "A3E3ED"),
            color_from_hex("Delta", "A4A49D"),
            color_from_hex("Wistful", "A4A6D3"),
            color_from_hex("Green Smoke", "A4AF6E"),
            color_from_hex("Jazzberry Jam", "A50B5E"),
            color_from_hex("Zorba", "A59B91"),
            color_from_hex("Bahia", "A5CB0C"),
            color_from_hex("Roof Terracotta", "A62F20"),
            color_from_hex("Paarl", "A65529"),
            color_from_hex("Barley Corn", "A68B5B"),
            color_from_hex("Donkey Brown", "A69279"),
            color_from_hex("Dawn", "A6A29A"),
            color_from_hex("Mexican Red", "A72525"),
            color_from_hex("Luxor Gold", "A7882C"),
            color_from_hex("Rich Gold", "A85307"),
            color_from_hex("Reno Sand", "A86515"),
            color_from_hex("Coral Tree", "A86B6B"),
            color_from_hex("Dusty Gray", "A8989B"),
            color_from_hex("Dull Lavender", "A899E6"),
            color_from_hex("Tallow", "A8A589"),
            color_from_hex("Bud", "A8AE9C"),
            color_from_hex("Locust", "A8AF8E"),
            color_from_hex("Norway", "A8BD9F"),
            color_from_hex("Chinook", "A8E3BD"),
            color_from_hex("Gray Olive", "A9A491"),
            color_from_hex("Aluminium", "A9ACB6"),
            color_from_hex("Cadet Blue", "A9B2C3"),
            color_from_hex("Schist", "A9B497"),
            color_from_hex("Tower Gray", "A9BDBF"),
            color_from_hex("Perano", "A9BEF2"),
            color_from_hex("Opal", "A9C6C2"),
            color_from_hex("Night Shadz", "AA375A"),
            color_from_hex("Fire", "AA4203"),
            color_from_hex("Muesli", "AA8B5B"),
            color_from_hex("Sandal", "AA8D6F"),
            color_from_hex("Shady Lady", "AAA5A9"),
            color_from_hex("Logan", "AAA9CD"),
            color_from_hex("Spun Pearl", "AAABB7"),
            color_from_hex("Regent St Blue", "AAD6E6"),
            color_from_hex("Magic Mint", "AAF0D1"),
            color_from_hex("Lipstick", "AB0563"),
            color_from_hex("Royal Heath", "AB3472"),
            color_from_hex("Sandrift", "AB917A"),
            color_from_hex("Cold Purple", "ABA0D9"),
            color_from_hex("Bronco", "ABA196"),
            color_from_hex("Limed Oak", "AC8A56"),
            color_from_hex("East Side", "AC91CE"),
            color_from_hex("Lemon Ginger", "AC9E22"),
            color_from_hex("Napa", "ACA494"),
            color_from_hex("Hillary", "ACA586"),
            color_from_hex("Cloudy", "ACA59F"),
            color_from_hex("Silver Chalice", "ACACAC"),
            color_from_hex("Swamp Green", "ACB78E"),
            color_from_hex("Spring Rain", "ACCBB1"),
            color_from_hex("Conifer", "ACDD4D"),
            color_from_hex("Celadon", "ACE1AF"),
            color_from_hex("Mandalay", "AD781B"),
            color_from_hex("Casper", "ADBED1"),
            color_from_hex("Moss Green", "ADDFAD"),
            color_from_hex("Padua", "ADE6C4"),
            color_from_hex("Green Yellow", "ADFF2F"),
            color_from_hex("Hippie Pink", "AE4560"),
            color_from_hex("Desert", "AE6020"),
            color_from_hex("Bouquet", "AE809E"),
            color_from_hex("Medium Carmine", "AF4035"),
            color_from_hex("Apple Blossom", "AF4D43"),
            color_from_hex("Brown Rust", "AF593E"),
            color_from_hex("Driftwood", "AF8751"),
            color_from_hex("Alpine", "AF8F2C"),
            color_from_hex("Lucky", "AF9F1C"),
            color_from_hex("Martini", "AFA09E"),
            color_from_hex("Bombay", "AFB1B8"),
            color_from_hex("Pigeon Post", "AFBDD9"),
            color_from_hex("Cadillac", "B04C6A"),
            color_from_hex("Matrix", "B05D54"),
            color_from_hex("Tapestry", "B05E81"),
            color_from_hex("Mai Tai", "B06608"),
            color_from_hex("Del Rio", "B09A95"),
            color_from_hex("Powder Blue", "B0E0E6"),
            color_from_hex("Inch Worm", "B0E313"),
            color_from_hex("Bright Red", "B10000"),
            color_from_hex("Vesuvius", "B14A0B"),
            color_from_hex("Pumpkin Skin", "B1610B"),
            color_from_hex("Santa Fe", "B16D52"),
            color_from_hex("Teak", "B19461"),
            color_from_hex("Fringy Flower", "B1E2C1"),
            color_from_hex("Ice Cold", "B1F4E7"),
            color_from_hex("Shiraz", "B20931"),
            color_from_hex("Biloba Flower", "B2A1EA"),
            color_from_hex("Tall Poppy", "B32D29"),
            color_from_hex("Fiery Orange", "B35213"),
            color_from_hex("Hot Toddy", "B38007"),
            color_from_hex("Taupe Gray", "B3AF95"),
            color_from_hex("La Rioja", "B3C110"),
            color_from_hex("Well Read", "B43332"),
            color_from_hex("Blush", "B44668"),
            color_from_hex("Jungle Mist", "B4CFD3"),
            color_from_hex("Turkish Rose", "B57281"),
            color_from_hex("Lavender", "B57EDC"),
            color_from_hex("Mongoose", "B5A27F"),
            color_from_hex("Olive Green", "B5B35C"),
            color_from_hex("Jet Stream", "B5D2CE"),
            color_from_hex("Cruise", "B5ECDF"),
            color_from_hex("Hibiscus", "B6316C"),
            color_from_hex("Thatch", "B69D98"),
            color_from_hex("Heathered Gray", "B6B095"),
            color_from_hex("Eagle", "B6BAA4"),
            color_from_hex("Spindle", "B6D1EA"),
            color_from_hex("Gum Leaf", "B6D3BF"),
            color_from_hex("Rust", "B7410E"),
            color_from_hex("Muddy Waters", "B78E5C"),
            color_from_hex("Sahara", "B7A214"),
            color_from_hex("Husk", "B7A458"),
            color_from_hex("Nobel", "B7B1B1"),
            color_from_hex("Heather", "B7C3D0"),
            color_from_hex("Madang", "B7F0BE"),
            color_from_hex("Milano Red", "B81104"),
            color_from_hex("Copper", "B87333"),
            color_from_hex("Gimblet", "B8B56A"),
            color_from_hex("Green Spring", "B8C1B1"),
            color_from_hex("Celery", "B8C25D"),
            color_from_hex("Sail", "B8E0F9"),
            color_from_hex("Chestnut", "B94E48"),
            color_from_hex("Crail", "B95140"),
            color_from_hex("Marigold", "B98D28"),
            color_from_hex("Wild Willow", "B9C46A"),
            color_from_hex("Rainee", "B9C8AC"),
            color_from_hex("Guardsman Red", "BA0101"),
            color_from_hex("Rock Spray", "BA450C"),
            color_from_hex("Bourbon", "BA6F1E"),
            color_from_hex("Pirate Gold", "BA7F03"),
            color_from_hex("Nomad", "BAB1A2"),
            color_from_hex("Submarine", "BAC7C9"),
            color_from_hex("Charlotte", "BAEEF9"),
            color_from_hex("Medium Red Violet", "BB3385"),
            color_from_hex("Brandy Rose", "BB8983"),
            color_from_hex("Rio Grande", "BBD009"),
            color_from_hex("Surf", "BBD7C1"),
            color_from_hex("Powder Ash", "BCC9C2"),
            color_from_hex("Tuscany", "BD5E2E"),
            color_from_hex("Quicksand", "BD978E"),
            color_from_hex("Silk", "BDB1A8"),
            color_from_hex("Malta", "BDB2A1"),
            color_from_hex("Chatelle", "BDB3C7"),
            color_from_hex("Lavender Gray", "BDBBD7"),
            color_from_hex("French Gray", "BDBDC6"),
            color_from_hex("Clay Ash", "BDC8B3"),
            color_from_hex("Loblolly", "BDC9CE"),
            color_from_hex("French Pass", "BDEDFD"),
            color_from_hex("London Hue", "BEA6C3"),
            color_from_hex("Pink Swan", "BEB5B7"),
            color_from_hex("Fuego", "BEDE0D"),
            color_from_hex("Rose of Sharon", "BF5500"),
            color_from_hex("Tide", "BFB8B0"),
            color_from_hex("Blue Haze", "BFBED8"),
            color_from_hex("Silver Sand", "BFC1C2"),
            color_from_hex("Key Lime Pie", "BFC921"),
            color_from_hex("Ziggurat", "BFDBE2"),
            color_from_hex("Lime", "BFFF00"),
            color_from_hex("Thunderbird", "C02B18"),
            color_from_hex("Mojo", "C04737"),
            color_from_hex("Old Rose", "C08081"),
            color_from_hex("Silver", "C0C0C0"),
            color_from_hex("Pale Leaf", "C0D3B9"),
            color_from_hex("Pixie Green", "C0D8B6"),
            color_from_hex("Tia Maria", "C1440E"),
            color_from_hex("Fuchsia Pink", "C154C1"),
            color_from_hex("Buddha Gold", "C1A004"),
            color_from_hex("Bison Hide", "C1B7A4"),
            color_from_hex("Tea", "C1BAB0"),
            color_from_hex("Gray Suit", "C1BECD"),
            color_from_hex("Sprout", "C1D7B0"),
            color_from_hex("Sulu", "C1F07C"),
            color_from_hex("Indochine", "C26B03"),
            color_from_hex("Twine", "C2955D"),
            color_from_hex("Cotton Seed", "C2BDB6"),
            color_from_hex("Pumice", "C2CAC4"),
            color_from_hex("Jagged Ice", "C2E8E5"),
            color_from_hex("Maroon Flush", "C32148"),
            color_from_hex("Indian Khaki", "C3B091"),
            color_from_hex("Pale Slate", "C3BFC1"),
            color_from_hex("Gray Nickel", "C3C3BD"),
            color_from_hex("Periwinkle Gray", "C3CDE6"),
            color_from_hex("Tiara", "C3D1D1"),
            color_from_hex("Tropical Blue", "C3DDF9"),
            color_from_hex("Cardinal", "C41E3A"),
            color_from_hex("Fuzzy Wuzzy Brown", "C45655"),
            color_from_hex("Orange Roughy", "C45719"),
            color_from_hex("Mist Gray", "C4C4BC"),
            color_from_hex("Coriander", "C4D0B0"),
            color_from_hex("Mint Tulip", "C4F4EB"),
            color_from_hex("Mulberry", "C54B8C"),
            color_from_hex("Nugget", "C59922"),
            color_from_hex("Tussock", "C5994B"),
            color_from_hex("Sea Mist", "C5DBCA"),
            color_from_hex("Yellow Green", "C5E17A"),
            color_from_hex("Brick Red", "C62D42"),
            color_from_hex("Contessa", "C6726B"),
            color_from_hex("Oriental Pink", "C69191"),
            color_from_hex("Roti", "C6A84B"),
            color_from_hex("Ash", "C6C3B5"),
            color_from_hex("Kangaroo", "C6C8BD"),
            color_from_hex("Las Palmas", "C6E610"),
            color_from_hex("Monza", "C7031E"),
            color_from_hex("Red Violet", "C71585"),
            color_from_hex("Coral Reef", "C7BCA2"),
            color_from_hex("Melrose", "C7C1FF"),
            color_from_hex("Cloud", "C7C4BF"),
            color_from_hex("Ghost", "C7C9D5"),
            color_from_hex("Pine Glade", "C7CD90"),
            color_from_hex("Botticelli", "C7DDE5"),
            color_from_hex("Antique Brass", "C88A65"),
            color_from_hex("Lilac", "C8A2C8"),
            color_from_hex("Hokey Pokey", "C8A528"),
            color_from_hex("Lily", "C8AABF"),
            color_from_hex("Laser", "C8B568"),
            color_from_hex("Edgewater", "C8E3D7"),
            color_from_hex("Piper", "C96323"),
            color_from_hex("Pizza", "C99415"),
            color_from_hex("Light Wisteria", "C9A0DC"),
            color_from_hex("Rodeo Dust", "C9B29B"),
            color_from_hex("Sundance", "C9B35B"),
            color_from_hex("Earls Green", "C9B93B"),
            color_from_hex("Silver Rust", "C9C0BB"),
            color_from_hex("Conch", "C9D9D2"),
            color_from_hex("Reef", "C9FFA2"),
            color_from_hex("Aero Blue", "C9FFE5"),
            color_from_hex("Flush Mahogany", "CA3435"),
            color_from_hex("Turmeric", "CABB48"),
            color_from_hex("Paris White", "CADCD4"),
            color_from_hex("Bitter Lemon", "CAE00D"),
            color_from_hex("Skeptic", "CAE6DA"),
            color_from_hex("Viola", "CB8FA9"),
            color_from_hex("Foggy Gray", "CBCAB6"),
            color_from_hex("Green Mist", "CBD3B0"),
            color_from_hex("Nebula", "CBDBD6"),
            color_from_hex("Persian Red", "CC3333"),
            color_from_hex("Burnt Orange", "CC5500"),
            color_from_hex("Ochre", "CC7722"),
            color_from_hex("Puce", "CC8899"),
            color_from_hex("Thistle Green", "CCCAA8"),
            color_from_hex("Periwinkle", "CCCCFF"),
            color_from_hex("Electric Lime", "CCFF00"),
            color_from_hex("Tenn", "CD5700"),
            color_from_hex("Chestnut Rose", "CD5C5C"),
            color_from_hex("Brandy Punch", "CD8429"),
            color_from_hex("Onahau", "CDF4FF"),
            color_from_hex("Sorrell Brown", "CEB98F"),
            color_from_hex("Cold Turkey", "CEBABA"),
            color_from_hex("Yuma", "CEC291"),
            color_from_hex("Chino", "CEC7A7"),
            color_from_hex("Eunry", "CFA39D"),
            color_from_hex("Old Gold", "CFB53B"),
            color_from_hex("Tasman", "CFDCCF"),
            color_from_hex("Surf Crest", "CFE5D2"),
            color_from_hex("Humming Bird", "CFF9F3"),
            color_from_hex("Scandal", "CFFAF4"),
            color_from_hex("Red Stage", "D05F04"),
            color_from_hex("Hopbush", "D06DA1"),
            color_from_hex("Meteor", "D07D12"),
            color_from_hex("Perfume", "D0BEF8"),
            color_from_hex("Prelude", "D0C0E5"),
            color_from_hex("Tea Green", "D0F0C0"),
            color_from_hex("Geebung", "D18F1B"),
            color_from_hex("Vanilla", "D1BEA8"),
            color_from_hex("Soft Amber", "D1C6B4"),
            color_from_hex("Celeste", "D1D2CA"),
            color_from_hex("Mischka", "D1D2DD"),
            color_from_hex("Pear", "D1E231"),
            color_from_hex("Hot Cinnamon", "D2691E"),
            color_from_hex("Raw Sienna", "D27D46"),
            color_from_hex("Careys Pink", "D29EAA"),
            color_from_hex("Tan", "D2B48C"),
            color_from_hex("Deco", "D2DA97"),
            color_from_hex("Blue Romance", "D2F6DE"),
            color_from_hex("Gossip", "D2F8B0"),
            color_from_hex("Sisal", "D3CBBA"),
            color_from_hex("Swirl", "D3CDC5"),
            color_from_hex("Charm", "D47494"),
            color_from_hex("Clam Shell", "D4B6AF"),
            color_from_hex("Straw", "D4BF8D"),
            color_from_hex("Akaroa", "D4C4A8"),
            color_from_hex("Bird Flower", "D4CD16"),
            color_from_hex("Iron", "D4D7D9"),
            color_from_hex("Geyser", "D4DFE2"),
            color_from_hex("Hawkes Blue", "D4E2FC"),
            color_from_hex("Grenadier", "D54600"),
            color_from_hex("Can Can", "D591A4"),
            color_from_hex("Whiskey", "D59A6F"),
            color_from_hex("Winter Hazel", "D5D195"),
            color_from_hex("Granny Apple", "D5F6E3"),
            color_from_hex("My Pink", "D69188"),
            color_from_hex("Tacha", "D6C562"),
            color_from_hex("Moon Raker", "D6CEF6"),
            color_from_hex("Quill Gray", "D6D6D1"),
            color_from_hex("Snowy Mint", "D6FFDB"),
            color_from_hex("New York Pink", "D7837F"),
            color_from_hex("Pavlova", "D7C498"),
            color_from_hex("Fog", "D7D0FF"),
            color_from_hex("Valencia", "D84437"),
            color_from_hex("Japonica", "D87C63"),
            color_from_hex("Thistle", "D8BFD8"),
            color_from_hex("Maverick", "D8C2D5"),
            color_from_hex("Foam", "D8FCFA"),
            color_from_hex("Cabaret", "D94972"),
            color_from_hex("Burning Sand", "D99376"),
            color_from_hex("Cameo", "D9B99B"),
            color_from_hex("Timberwolf", "D9D6CF"),
            color_from_hex("Tana", "D9DCC1"),
            color_from_hex("Link Water", "D9E4F5"),
            color_from_hex("Mabel", "D9F7FF"),
            color_from_hex("Cerise", "DA3287"),
            color_from_hex("Flame Pea", "DA5B38"),
            color_from_hex("Bamboo", "DA6304"),
            color_from_hex("Red Damask", "DA6A41"),
            color_from_hex("Orchid", "DA70D6"),
            color_from_hex("Copperfield", "DA8A67"),
            color_from_hex("Golden Grass", "DAA520"),
            color_from_hex("Zanah", "DAECD6"),
            color_from_hex("Iceberg", "DAF4F0"),
            color_from_hex("Oyster Bay", "DAFAFF"),
            color_from_hex("Cranberry", "DB5079"),
            color_from_hex("Petite Orchid", "DB9690"),
            color_from_hex("Di Serria", "DB995E"),
            color_from_hex("Alto", "DBDBDB"),
            color_from_hex("Frosted Mint", "DBFFF8"),
            color_from_hex("Crimson", "DC143C"),
            color_from_hex("Punch", "DC4333"),
            color_from_hex("Galliano", "DCB20C"),
            color_from_hex("Blossom", "DCB4BC"),
            color_from_hex("Wattle", "DCD747"),
            color_from_hex("Westar", "DCD9D2"),
            color_from_hex("Moon Mist", "DCDDCC"),
            color_from_hex("Caper", "DCEDB4"),
            color_from_hex("Swans Down", "DCF0EA"),
            color_from_hex("Swiss Coffee", "DDD6D5"),
            color_from_hex("White Ice", "DDF9F1"),
            color_from_hex("Cerise Red", "DE3163"),
            color_from_hex("Roman", "DE6360"),
            color_from_hex("Tumbleweed", "DEA681"),
            color_from_hex("Gold Tips", "DEBA13"),
            color_from_hex("Brandy", "DEC196"),
            color_from_hex("Wafer", "DECBC6"),
            color_from_hex("Sapling", "DED4A4"),
            color_from_hex("Barberry", "DED717"),
            color_from_hex("Beryl Green", "DEE5C0"),
            color_from_hex("Pattens Blue", "DEF5FF"),
            color_from_hex("Heliotrope", "DF73FF"),
            color_from_hex("Apache", "DFBE6F"),
            color_from_hex("Chenin", "DFCD6F"),
            color_from_hex("Lola", "DFCFDB"),
            color_from_hex("Willow Brook", "DFECDA"),
            color_from_hex("Chartreuse Yellow", "DFFF00"),
            color_from_hex("Mauve", "E0B0FF"),
            color_from_hex("Anzac", "E0B646"),
            color_from_hex("Harvest Gold", "E0B974"),
            color_from_hex("Calico", "E0C095"),
            color_from_hex("Baby Blue", "E0FFFF"),
            color_from_hex("Sunglo", "E16865"),
            color_from_hex("Equator", "E1BC64"),
            color_from_hex("Pink Flare", "E1C0C8"),
            color_from_hex("Periglacial Blue", "E1E6D6"),
            color_from_hex("Kidnapper", "E1EAD4"),
            color_from_hex("Tara", "E1F6E8"),
            color_from_hex("Mandy", "E25465"),
            color_from_hex("Terracotta", "E2725B"),
            color_from_hex("Golden Bell", "E28913"),
            color_from_hex("Shocking", "E292C0"),
            color_from_hex("Dixie", "E29418"),
            color_from_hex("Light Orchid", "E29CD2"),
            color_from_hex("Snuff", "E2D8ED"),
            color_from_hex("Mystic", "E2EBED"),
            color_from_hex("Apple Green", "E2F3EC"),
            color_from_hex("Razzmatazz", "E30B5C"),
            color_from_hex("Alizarin Crimson", "E32636"),
            color_from_hex("Cinnabar", "E34234"),
            color_from_hex("Cavern Pink", "E3BEBE"),
            color_from_hex("Peppermint", "E3F5E1"),
            color_from_hex("Mindaro", "E3F988"),
            color_from_hex("Deep Blush", "E47698"),
            color_from_hex("Gamboge", "E49B0F"),
            color_from_hex("Melanie", "E4C2D5"),
            color_from_hex("Twilight", "E4CFDE"),
            color_from_hex("Bone", "E4D1C0"),
            color_from_hex("Sunflower", "E4D422"),
            color_from_hex("Grain Brown", "E4D5B7"),
            color_from_hex("Zombie", "E4D69B"),
            color_from_hex("Frostee", "E4F6E7"),
            color_from_hex("Snow Flurry", "E4FFD1"),
            color_from_hex("Amaranth", "E52B50"),
            color_from_hex("Zest", "E5841B"),
            color_from_hex("Dust Storm", "E5CCC9"),
            color_from_hex("Stark White", "E5D7BD"),
            color_from_hex("Hampton", "E5D8AF"),
            color_from_hex("Bon Jour", "E5E0E1"),
            color_from_hex("Mercury", "E5E5E5"),
            color_from_hex("Polar", "E5F9F6"),
            color_from_hex("Trinidad", "E64E03"),
            color_from_hex("Gold Sand", "E6BE8A"),
            color_from_hex("Cashmere", "E6BEA5"),
            color_from_hex("Double Spanish White", "E6D7B9"),
            color_from_hex("Satin Linen", "E6E4D4"),
            color_from_hex("Harp", "E6F2EA"),
            color_from_hex("Off Green", "E6F8F3"),
            color_from_hex("Hint of Green", "E6FFE9"),
            color_from_hex("Tranquil", "E6FFFF"),
            color_from_hex("Mango Tango", "E77200"),
            color_from_hex("Christine", "E7730A"),
            color_from_hex("Tonys Pink", "E79F8C"),
            color_from_hex("Kobi", "E79FC4"),
            color_from_hex("Rose Fog", "E7BCB4"),
            color_from_hex("Corn", "E7BF05"),
            color_from_hex("Putty", "E7CD8C"),
            color_from_hex("Gray Nurse", "E7ECE6"),
            color_from_hex("Lily White", "E7F8FF"),
            color_from_hex("Bubbles", "E7FEFF"),
            color_from_hex("Fire Bush", "E89928"),
            color_from_hex("Shilo", "E8B9B3"),
            color_from_hex("Pearl Bush", "E8E0D5"),
            color_from_hex("Green White", "E8EBE0"),
            color_from_hex("Chrome White", "E8F1D4"),
            color_from_hex("Gin", "E8F2EB"),
            color_from_hex("Aqua Squeeze", "E8F5F2"),
            color_from_hex("Clementine", "E96E00"),
            color_from_hex("Burnt Sienna", "E97451"),
            color_from_hex("Tahiti Gold", "E97C07"),
            color_from_hex("Oyster Pink", "E9CECD"),
            color_from_hex("Confetti", "E9D75A"),
            color_from_hex("Ebb", "E9E3E3"),
            color_from_hex("Ottoman", "E9F8ED"),
            color_from_hex("Clear Day", "E9FFFD"),
            color_from_hex("Carissma", "EA88A8"),
            color_from_hex("Porsche", "EAAE69"),
            color_from_hex("Tulip Tree", "EAB33B"),
            color_from_hex("Rob Roy", "EAC674"),
            color_from_hex("Raffia", "EADAB8"),
            color_from_hex("White Rock", "EAE8D4"),
            color_from_hex("Panache", "EAF6EE"),
            color_from_hex("Solitude", "EAF6FF"),
            color_from_hex("Aqua Spring", "EAF9F5"),
            color_from_hex("Dew", "EAFFFE"),
            color_from_hex("Apricot", "EB9373"),
            color_from_hex("Zinnwaldite", "EBC2AF"),
            color_from_hex("Fuel Yellow", "ECA927"),
            color_from_hex("Ronchi", "ECC54E"),
            color_from_hex("French Lilac", "ECC7EE"),
            color_from_hex("Just Right", "ECCDB9"),
            color_from_hex("Wild Rice", "ECE090"),
            color_from_hex("Fall Green", "ECEBBD"),
            color_from_hex("Aths Special", "ECEBCE"),
            color_from_hex("Starship", "ECF245"),
            color_from_hex("Red Ribbon", "ED0A3F"),
            color_from_hex("Tango", "ED7A1C"),
            color_from_hex("Carrot Orange", "ED9121"),
            color_from_hex("Sea Pink", "ED989E"),
            color_from_hex("Tacao", "EDB381"),
            color_from_hex("Desert Sand", "EDC9AF"),
            color_from_hex("Pancho", "EDCDAB"),
            color_from_hex("Chamois", "EDDCB1"),
            color_from_hex("Primrose", "EDEA99"),
            color_from_hex("Frost", "EDF5DD"),
            color_from_hex("Aqua Haze", "EDF5F5"),
            color_from_hex("Zumthor", "EDF6FF"),
            color_from_hex("Narvik", "EDF9F1"),
            color_from_hex("Honeysuckle", "EDFC84"),
            color_from_hex("Lavender Magenta", "EE82EE"),
            color_from_hex("Beauty Bush", "EEC1BE"),
            color_from_hex("Chalky", "EED794"),
            color_from_hex("Almond", "EED9C4"),
            color_from_hex("Flax", "EEDC82"),
            color_from_hex("Bizarre", "EEDEDA"),
            color_from_hex("Double Colonial White", "EEE3AD"),
            color_from_hex("Cararra", "EEEEE8"),
            color_from_hex("Manz", "EEEF78"),
            color_from_hex("Tahuna Sands", "EEF0C8"),
            color_from_hex("Athens Gray", "EEF0F3"),
            color_from_hex("Tusk", "EEF3C3"),
            color_from_hex("Loafer", "EEF4DE"),
            color_from_hex("Catskill White", "EEF6F7"),
            color_from_hex("Twilight Blue", "EEFDFF"),
            color_from_hex("Jonquil", "EEFF9A"),
            color_from_hex("Rice Flower", "EEFFE2"),
            color_from_hex("Jaffa", "EF863F"),
            color_from_hex("Gallery", "EFEFEF"),
            color_from_hex("Porcelain", "EFF2F3"),
            color_from_hex("Mauvelous", "F091A9"),
            color_from_hex("Golden Dream", "F0D52D"),
            color_from_hex("Golden Sand", "F0DB7D"),
            color_from_hex("Buff", "F0DC82"),
            color_from_hex("Prim", "F0E2EC"),
            color_from_hex("Khaki", "F0E68C"),
            color_from_hex("Selago", "F0EEFD"),
            color_from_hex("Titan White", "F0EEFF"),
            color_from_hex("Alice Blue", "F0F8FF"),
            color_from_hex("Feta", "F0FCEA"),
            color_from_hex("Gold Drop", "F18200"),
            color_from_hex("Wewak", "F19BAB"),
            color_from_hex("Sahara Sand", "F1E788"),
            color_from_hex("Parchment", "F1E9D2"),
            color_from_hex("Blue Chalk", "F1E9FF"),
            color_from_hex("Mint Julep", "F1EEC1"),
            color_from_hex("Seashell", "F1F1F1"),
            color_from_hex("Saltpan", "F1F7F2"),
            color_from_hex("Tidal", "F1FFAD"),
            color_from_hex("Chiffon", "F1FFC8"),
            color_from_hex("Flamingo", "F2552A"),
            color_from_hex("Tangerine", "F28500"),
            color_from_hex("Mandys Pink", "F2C3B2"),
            color_from_hex("Concrete", "F2F2F2"),
            color_from_hex("Black Squeeze", "F2FAFA"),
            color_from_hex("Pomegranate", "F34723"),
            color_from_hex("Buttercup", "F3AD16"),
            color_from_hex("New Orleans", "F3D69D"),
            color_from_hex("Vanilla Ice", "F3D9DF"),
            color_from_hex("Sidecar", "F3E7BB"),
            color_from_hex("Dawn Pink", "F3E9E5"),
            color_from_hex("Wheatfield", "F3EDCF"),
            color_from_hex("Canary", "F3FB62"),
            color_from_hex("Orinoco", "F3FBD4"),
            color_from_hex("Carla", "F3FFD8"),
            color_from_hex("Hollywood Cerise", "F400A1"),
            color_from_hex("Sandy brown", "F4A460"),
            color_from_hex("Saffron", "F4C430"),
            color_from_hex("Ripe Lemon", "F4D81C"),
            color_from_hex("Janna", "F4EBD3"),
            color_from_hex("Pampas", "F4F2EE"),
            color_from_hex("Wild Sand", "F4F4F4"),
            color_from_hex("Zircon", "F4F8FF"),
            color_from_hex("Froly", "F57584"),
            color_from_hex("Cream Can", "F5C85C"),
            color_from_hex("Manhattan", "F5C999"),
            color_from_hex("Maize", "F5D5A0"),
            color_from_hex("Wheat", "F5DEB3"),
            color_from_hex("Sandwisp", "F5E7A2"),
            color_from_hex("Pot Pourri", "F5E7E2"),
            color_from_hex("Albescent White", "F5E9D3"),
            color_from_hex("Soft Peach", "F5EDEF"),
            color_from_hex("Ecru White", "F5F3E5"),
            color_from_hex("Beige", "F5F5DC"),
            color_from_hex("Golden Fizz", "F5FB3D"),
            color_from_hex("Australian Mint", "F5FFBE"),
            color_from_hex("French Rose", "F64A8A"),
            color_from_hex("Brilliant Rose", "F653A6"),
            color_from_hex("Illusion", "F6A4C9"),
            color_from_hex("Merino", "F6F0E6"),
            color_from_hex("Black Haze", "F6F7F7"),
            color_from_hex("Spring Sun", "F6FFDC"),
            color_from_hex("Violet Red", "F7468A"),
            color_from_hex("Chilean Fire", "F77703"),
            color_from_hex("Persian Pink", "F77FBE"),
            color_from_hex("Rajah", "F7B668"),
            color_from_hex("Azalea", "F7C8DA"),
            color_from_hex("We Peep", "F7DBE6"),
            color_from_hex("Quarter Spanish White", "F7F2E1"),
            color_from_hex("Whisper", "F7F5FA"),
            color_from_hex("Snow Drift", "F7FAF7"),
            color_from_hex("Casablanca", "F8B853"),
            color_from_hex("Chantilly", "F8C3DF"),
            color_from_hex("Cherub", "F8D9E9"),
            color_from_hex("Marzipan", "F8DB9D"),
            color_from_hex("Energy Yellow", "F8DD5C"),
            color_from_hex("Givry", "F8E4BF"),
            color_from_hex("White Linen", "F8F0E8"),
            color_from_hex("Magnolia", "F8F4FF"),
            color_from_hex("Spring Wood", "F8F6F1"),
            color_from_hex("Coconut Cream", "F8F7DC"),
            color_from_hex("White Lilac", "F8F7FC"),
            color_from_hex("Desert Storm", "F8F8F7"),
            color_from_hex("Texas", "F8F99C"),
            color_from_hex("Corn Field", "F8FACD"),
            color_from_hex("Mimosa", "F8FDD3"),
            color_from_hex("Carnation", "F95A61"),
            color_from_hex("Saffron Mango", "F9BF58"),
            color_from_hex("Carousel Pink", "F9E0ED"),
            color_from_hex("Dairy Cream", "F9E4BC"),
            color_from_hex("Portica", "F9E663"),
            color_from_hex("Amour", "F9EAF3"),
            color_from_hex("Rum Swizzle", "F9F8E4"),
            color_from_hex("Dolly", "F9FF8B"),
            color_from_hex("Sugar Cane", "F9FFF6"),
            color_from_hex("Ecstasy", "FA7814"),
            color_from_hex("Tan Hide", "FA9D5A"),
            color_from_hex("Corvette", "FAD3A2"),
            color_from_hex("Peach Yellow", "FADFAD"),
            color_from_hex("Turbo", "FAE600"),
            color_from_hex("Astra", "FAEAB9"),
            color_from_hex("Champagne", "FAECCC"),
            color_from_hex("Linen", "FAF0E6"),
            color_from_hex("Fantasy", "FAF3F0"),
            color_from_hex("Citrine White", "FAF7D6"),
            color_from_hex("Alabaster", "FAFAFA"),
            color_from_hex("Hint of Yellow", "FAFDE4"),
            color_from_hex("Milan", "FAFFA4"),
            color_from_hex("Brink Pink", "FB607F"),
            color_from_hex("Geraldine", "FB8989"),
            color_from_hex("Lavender Rose", "FBA0E3"),
            color_from_hex("Sea Buckthorn", "FBA129"),
            color_from_hex("Sun", "FBAC13"),
            color_from_hex("Lavender Pink", "FBAED2"),
            color_from_hex("Rose Bud", "FBB2A3"),
            color_from_hex("Cupid", "FBBEDA"),
            color_from_hex("Classic Rose", "FBCCE7"),
            color_from_hex("Apricot Peach", "FBCEB1"),
            color_from_hex("Banana Mania", "FBE7B2"),
            color_from_hex("Marigold Yellow", "FBE870"),
            color_from_hex("Festival", "FBE96C"),
            color_from_hex("Sweet Corn", "FBEA8C"),
            color_from_hex("Candy Corn", "FBEC5D"),
            color_from_hex("Hint of Red", "FBF9F9"),
            color_from_hex("Shalimar", "FBFFBA"),
            color_from_hex("Shocking Pink", "FC0FC0"),
            color_from_hex("Tickle Me Pink", "FC80A5"),
            color_from_hex("Tree Poppy", "FC9C1D"),
            color_from_hex("Lightning Yellow", "FCC01E"),
            color_from_hex("Goldenrod", "FCD667"),
            color_from_hex("Candlelight", "FCD917"),
            color_from_hex("Cherokee", "FCDA98"),
            color_from_hex("Double Pearl Lusta", "FCF4D0"),
            color_from_hex("Pearl Lusta", "FCF4DC"),
            color_from_hex("Vista White", "FCF8F7"),
            color_from_hex("Bianca", "FCFBF3"),
            color_from_hex("Moon Glow", "FCFEDA"),
            color_from_hex("China Ivory", "FCFFE7"),
            color_from_hex("Ceramic", "FCFFF9"),
            color_from_hex("Torch Red", "FD0E35"),
            color_from_hex("Wild Watermelon", "FD5B78"),
            color_from_hex("Crusta", "FD7B33"),
            color_from_hex("Sorbus", "FD7C07"),
            color_from_hex("Sweet Pink", "FD9FA2"),
            color_from_hex("Light Apricot", "FDD5B1"),
            color_from_hex("Pig Pink", "FDD7E4"),
            color_from_hex("Cinderella", "FDE1DC"),
            color_from_hex("Golden Glow", "FDE295"),
            color_from_hex("Lemon", "FDE910"),
            color_from_hex("Old Lace", "FDF5E6"),
            color_from_hex("Half Colonial White", "FDF6D3"),
            color_from_hex("Drover", "FDF7AD"),
            color_from_hex("Pale Prim", "FDFEB8"),
            color_from_hex("Cumulus", "FDFFD5"),
            color_from_hex("Persian Rose", "FE28A2"),
            color_from_hex("Sunset Orange", "FE4C40"),
            color_from_hex("Bittersweet", "FE6F5E"),
            color_from_hex("California", "FE9D04"),
            color_from_hex("Yellow Sea", "FEA904"),
            color_from_hex("Melon", "FEBAAD"),
            color_from_hex("Bright Sun", "FED33C"),
            color_from_hex("Dandelion", "FED85D"),
            color_from_hex("Salomie", "FEDB8D"),
            color_from_hex("Cape Honey", "FEE5AC"),
            color_from_hex("Remy", "FEEBF3"),
            color_from_hex("Oasis", "FEEFCE"),
            color_from_hex("Bridesmaid", "FEF0EC"),
            color_from_hex("Beeswax", "FEF2C7"),
            color_from_hex("Bleach White", "FEF3D8"),
            color_from_hex("Pipi", "FEF4CC"),
            color_from_hex("Half Spanish White", "FEF4DB"),
            color_from_hex("Wisp Pink", "FEF4F8"),
            color_from_hex("Provincial Pink", "FEF5F1"),
            color_from_hex("Half Dutch White", "FEF7DE"),
            color_from_hex("Solitaire", "FEF8E2"),
            color_from_hex("White Pointer", "FEF8FF"),
            color_from_hex("Off Yellow", "FEF9E3"),
            color_from_hex("Orange White", "FEFCED"),
            color_from_hex("Red", "FF0000"),
            color_from_hex("Rose", "FF007F"),
            color_from_hex("Purple Pizzazz", "FF00CC"),
            color_from_hex("Magenta / Fuchsia", "FF00FF"),
            color_from_hex("Scarlet", "FF2400"),
            color_from_hex("Wild Strawberry", "FF3399"),
            color_from_hex("Razzle Dazzle Rose", "FF33CC"),
            color_from_hex("Radical Red", "FF355E"),
            color_from_hex("Red Orange", "FF3F34"),
            color_from_hex("Coral Red", "FF4040"),
            color_from_hex("Vermilion", "FF4D00"),
            color_from_hex("International Orange", "FF4F00"),
            color_from_hex("Outrageous Orange", "FF6037"),
            color_from_hex("Blaze Orange", "FF6600"),
            color_from_hex("Pink Flamingo", "FF66FF"),
            color_from_hex("Orange", "FF681F"),
            color_from_hex("Hot Pink", "FF69B4"),
            color_from_hex("Persimmon", "FF6B53"),
            color_from_hex("Blush Pink", "FF6FFF"),
            color_from_hex("Burning Orange", "FF7034"),
            color_from_hex("Pumpkin", "FF7518"),
            color_from_hex("Flamenco", "FF7D07"),
            color_from_hex("Flush Orange", "FF7F00"),
            color_from_hex("Coral", "FF7F50"),
            color_from_hex("Salmon", "FF8C69"),
            color_from_hex("Pizazz", "FF9000"),
            color_from_hex("West Side", "FF910F"),
            color_from_hex("Pink Salmon", "FF91A4"),
            color_from_hex("Neon Carrot", "FF9933"),
            color_from_hex("Atomic Tangerine", "FF9966"),
            color_from_hex("Vivid Tangerine", "FF9980"),
            color_from_hex("Sunshade", "FF9E2C"),
            color_from_hex("Orange Peel", "FFA000"),
            color_from_hex("Mona Lisa", "FFA194"),
            color_from_hex("Web Orange", "FFA500"),
            color_from_hex("Carnation Pink", "FFA6C9"),
            color_from_hex("Hit Pink", "FFAB81"),
            color_from_hex("Yellow Orange", "FFAE42"),
            color_from_hex("Cornflower Lilac", "FFB0AC"),
            color_from_hex("Sundown", "FFB1B3"),
            color_from_hex("My Sin", "FFB31F"),
            color_from_hex("Texas Rose", "FFB555"),
            color_from_hex("Cotton Candy", "FFB7D5"),
            color_from_hex("Macaroni and Cheese", "FFB97B"),
            color_from_hex("Selective Yellow", "FFBA00"),
            color_from_hex("Koromiko", "FFBD5F"),
            color_from_hex("Amber", "FFBF00"),
            color_from_hex("Wax Flower", "FFC0A8"),
            color_from_hex("Pink", "FFC0CB"),
            color_from_hex("Your Pink", "FFC3C0"),
            color_from_hex("Supernova", "FFC901"),
            color_from_hex("Flesh", "FFCBA4"),
            color_from_hex("Sunglow", "FFCC33"),
            color_from_hex("Golden Tainoi", "FFCC5C"),
            color_from_hex("Peach Orange", "FFCC99"),
            color_from_hex("Chardonnay", "FFCD8C"),
            color_from_hex("Pastel Pink", "FFD1DC"),
            color_from_hex("Romantic", "FFD2B7"),
            color_from_hex("Grandis", "FFD38C"),
            color_from_hex("Gold", "FFD700"),
            color_from_hex("School bus Yellow", "FFD800"),
            color_from_hex("Cosmos", "FFD8D9"),
            color_from_hex("Mustard", "FFDB58"),
            color_from_hex("Peach Schnapps", "FFDCD6"),
            color_from_hex("Caramel", "FFDDAF"),
            color_from_hex("Tuft Bush", "FFDDCD"),
            color_from_hex("Watusi", "FFDDCF"),
            color_from_hex("Pink Lace", "FFDDF4"),
            color_from_hex("Navajo White", "FFDEAD"),
            color_from_hex("Frangipani", "FFDEB3"),
            color_from_hex("Pippin", "FFE1DF"),
            color_from_hex("Pale Rose", "FFE1F2"),
            color_from_hex("Negroni", "FFE2C5"),
            color_from_hex("Cream Brulee", "FFE5A0"),
            color_from_hex("Peach", "FFE5B4"),
            color_from_hex("Tequila", "FFE6C7"),
            color_from_hex("Kournikova", "FFE772"),
            color_from_hex("Sandy Beach", "FFEAC8"),
            color_from_hex("Karry", "FFEAD4"),
            color_from_hex("Broom", "FFEC13"),
            color_from_hex("Colonial White", "FFEDBC"),
            color_from_hex("Derby", "FFEED8"),
            color_from_hex("Vis Vis", "FFEFA1"),
            color_from_hex("Egg White", "FFEFC1"),
            color_from_hex("Papaya Whip", "FFEFD5"),
            color_from_hex("Fair Pink", "FFEFEC"),
            color_from_hex("Peach Cream", "FFF0DB"),
            color_from_hex("Lavender blush", "FFF0F5"),
            color_from_hex("Gorse", "FFF14F"),
            color_from_hex("Buttermilk", "FFF1B5"),
            color_from_hex("Pink Lady", "FFF1D8"),
            color_from_hex("Forget Me Not", "FFF1EE"),
            color_from_hex("Tutu", "FFF1F9"),
            color_from_hex("Picasso", "FFF39D"),
            color_from_hex("Chardon", "FFF3F1"),
            color_from_hex("Paris Daisy", "FFF46E"),
            color_from_hex("Barley White", "FFF4CE"),
            color_from_hex("Egg Sour", "FFF4DD"),
            color_from_hex("Sazerac", "FFF4E0"),
            color_from_hex("Serenade", "FFF4E8"),
            color_from_hex("Chablis", "FFF4F3"),
            color_from_hex("Seashell Peach", "FFF5EE"),
            color_from_hex("Sauvignon", "FFF5F3"),
            color_from_hex("Milk Punch", "FFF6D4"),
            color_from_hex("Varden", "FFF6DF"),
            color_from_hex("Rose White", "FFF6F5"),
            color_from_hex("Baja White", "FFF8D1"),
            color_from_hex("Gin Fizz", "FFF9E2"),
            color_from_hex("Early Dawn", "FFF9E6"),
            color_from_hex("Lemon Chiffon", "FFFACD"),
            color_from_hex("Bridal Heath", "FFFAF4"),
            color_from_hex("Scotch Mist", "FFFBDC"),
            color_from_hex("Soapstone", "FFFBF9"),
            color_from_hex("Witch Haze", "FFFC99"),
            color_from_hex("Buttery White", "FFFCEA"),
            color_from_hex("Island Spice", "FFFCEE"),
            color_from_hex("Cream", "FFFDD0"),
            color_from_hex("Chilean Heath", "FFFDE6"),
            color_from_hex("Travertine", "FFFDE8"),
            color_from_hex("Orchid White", "FFFDF3"),
            color_from_hex("Quarter Pearl Lusta", "FFFDF4"),
            color_from_hex("Half and Half", "FFFEE1"),
            color_from_hex("Apricot White", "FFFEEC"),
            color_from_hex("Rice Cake", "FFFEF0"),
            color_from_hex("Black White", "FFFEF6"),
            color_from_hex("Romance", "FFFEFD"),
            color_from_hex("Yellow", "FFFF00"),
            color_from_hex("Laser Lemon", "FFFF66"),
            color_from_hex("Pale Canary", "FFFF99"),
            color_from_hex("Portafino", "FFFFB4"),
            color_from_hex("Ivory", "FFFFF0"),
            color_from_hex("White", "FFFFFF")
        ]
    }
}
